run:
  timeout: 5m
  allow-parallel-runners: true
linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
linters-settings:
  gocyclo:
    min-complexity: 40
  errcheck:
    check-type-assertions: true
    check-blank: true
issues:
  exclude-rules:
    - linters:
        - errcheck
      path: "k8smultiarcher.go"
      text: "Error return value of `r.Run` is not checked"
    - linters:
        - errcheck
      path: "k8smultiarcher.go"
      text: "Error return value of `r.RunTLS` is not checked"
